// Use ISO alpha-3 country codes, see e.g. https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
COUNTRIES =
{
    ITA: {fillKey: 'visited'},
    NOR: {fillKey: 'visited'},
    NZL: {fillKey: 'visited'},
    GRC: {fillKey: 'visited'},
    THA: {fillKey: 'visited'},
    POL: {fillKey: 'visited'},
    AUS: {fillKey: 'visited'},
    AUT: {fillKey: 'visited'},
    PRT: {fillKey: 'visited'},
    HRV: {fillKey: 'visited'},
    BEL: {fillKey: 'visited'},
    HUN: {fillKey: 'visited'},
    ROU: {fillKey: 'visited'},
    BGR: {fillKey: 'visited'},
    IRL: {fillKey: 'visited'},
    BIH: {fillKey: 'visited'},
    ISL: {fillKey: 'visited'},
    SRB: {fillKey: 'visited'},
    CHE: {fillKey: 'visited'},
    SVK: {fillKey: 'visited'},
    SVN: {fillKey: 'visited'},
    SWE: {fillKey: 'visited'},
    LTU: {fillKey: 'visited'},
    LUX: {fillKey: 'visited'},
    LVA: {fillKey: 'visited'},
    MCO: {fillKey: 'visited'},
    CZE: {fillKey: 'visited'},
    DEU: {fillKey: 'visited'},
    TUR: {fillKey: 'visited'},
    DNK: {fillKey: 'visited'},
    ESP: {fillKey: 'visited'},
    EST: {fillKey: 'visited'},
    VAT: {fillKey: 'visited'},
    FIN: {fillKey: 'visited'},
    FRA: {fillKey: 'visited'},
    VUT: {fillKey: 'visited'},
    GBR: {fillKey: 'visited'},
    NLD: {fillKey: 'visited'},
    MYS: {fillKey: 'visited'},
}
